services:
  - type: web
    name: echo-agent
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://echouser:jeJv2tBOKWrXYes8A9ES8UZWt4t8HQrq@dpg-d11kagfdiees73ffoe6g-a.oregon-postgres.render.com/echodb_wa4f
